[build]
command = "npm run build:ci"

[build.upload]
format = "directory"

[site]
bucket = "./dist"
entry-point = "."

[env.production]
name = "daniel-portfolio"

[env.preview]
name = "daniel-portfolio-preview" 